### ISSUE TITLE
Uncaught Error: traverseParentPath(...): Cannot traverse from and to the same ID, ``.

### ISSUE THREAD

**Issue by cyruslk** [YPlan/react-sticky-stack#4] opened 2017-05-28 16:02 UTC
Hello, 

I'm beginning with react and your npm seems exactly the one that I want for a project I'm working on! But unfortunately, I also have the same error : **Uncaught Error: traverseParentPath(...): Cannot traverse from and to the same ID, ``.**

What should I do to fix this?
Thank you very much for this wonderful package 👍 

Cyrus

Here's my code below:

`import React, { Component } from 'react';
import {StickyStackContext, StickyStackItem} from 'react-sticky-stack';

class FixedImgs extends Component {

  render() {
    return (

      <div className="FixedImg">

        <StickyStackContext>

          <StickyStackItem >
              <h1 className="sticky_1">sticky_1</h1>
          </StickyStackItem>

          <StickyStackItem >
              <h1 className="sticky_2">sticky_2</h1>
          </StickyStackItem>

        </StickyStackContext>

      </div>

    );
  }
}

export default FixedImgs;
`

**Comment by MicheleBertoli** [comment] 2017-05-28 16:15
Thanks @cyruslognonne, closing this as a duplicate of #2.

**Comment by MicheleBertoli** [comment] 2017-05-28 16:16
Thanks @cyruslognonne, this is a duplicate of #2.

**Comment by MicheleBertoli** [comment] 2017-05-28 16:17
Thanks @cyruslognonne, this is a duplicate of #2.

(apparently, I can't close issues on this repo - can you please help @adamchainz?)

**Closed as completed** 2017-05-28 17:00 UTC
